### PR TITLE
subscriber: fix incorrect formatter docs

### LINKED ISSUE #1880: Documentation for `Compact` and `Full` formats is wrong
### Version

tracing-subscriber v0.3.7

### Crates

tracing-subscriber

### Description

The [documentation for `Compact`](https://docs.rs/tracing-subscriber/0.3.7/tracing_subscriber/fmt/format/struct.Compact.html) says

> The compact format only includes the fields from the most recently entered span.

The [documentation for `Full`](https://docs.rs/tracing-subscriber/0.3.7/tracing_subscriber/fmt/format/struct.Full.html) says

> The full format includes fields from all entered spans.

This distinction here is wrong. `Compact` in fact includes fields from all spans. It just moves the fields to the end of the event, after the event's kv pairs.

### PR DESCRIPTION
**Pull request by hawkw**
This fixes outdated statements in the docs for the `Full` and `Compact`
logging formats.

Closes #1880.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

File: tracing-subscriber/src/fmt/format/mod.rs [hunk 1]
```diff
@@ -301,13 +301,18 @@ pub struct FieldFnVisitor<'a, F> {
 }
 /// Marker for `Format` that indicates that the compact log format should be used.
 ///
-/// The compact format only includes the fields from the most recently entered span.
+/// The compact format includes fields from all currently entered spans, after
+/// the event's fields. Span fields are not grouped by span, and span names are
+/// not shown. In addition, a more compact representation of each event's
+/// [`Level`](tracing::Level)
+/// is used.
```
Comment (hawkw) [inline tracing-subscriber/src/fmt/format/mod.rs:308]: weird:
```suggestion
/// [`Level`](tracing::Level) is used.
```

**Review by davidbarsky — APPROVED** [review]
