### PR TITLE
tracing: make `Entered` `!Send`

### LINKED ISSUE #698: tracing: `Entered` guards should be `!Send`
### Version

- all

### Crates

- `tracing`

### Description
The `Entered` guard returned by `Span::enter` represents entering and exiting a span _on the current thread_. Calling `Span::enter` enters the span, returning an `Entered`, and dropping the `Entered` ensures that the span is exited. This ensures that all spans, once entered, are eventually exited. 

However, `Entered` has an auto-impl of `Send`, because it doesn't contain any `!Send` types. This means that the `Entered` guard _could_ be sent to another thread and dropped. This would cause the original thread to never exit the span,. and the thread to which the `Entered` guard was sent would exit a span that it never observed an enter for. This is incorrect.

We should consider making `Entered` `!Send`. _Technically_, this is a breaking change, but the current behavior is incorrect. This would also prevent `Entered` guards from being held in futures that are bounded with `Send`, which would prevent _some_ incorrect uses of `Span::enter` in `async` blocks...

### PR DESCRIPTION
**Pull request by hawkw**
## Motivation

The `Entered` guard returned by `Span::enter` represents entering and
exiting a span _on the current thread_. Calling `Span::enter` enters the
span, returning an `Entered`, and dropping the `Entered` ensures that
the span is exited. This ensures that all spans, once entered, are
eventually exited.

However, `Entered` has an auto-impl of `Send`, because it doesn't
contain any `!Send` types. This means that the `Entered` guard _could_
be sent to another thread and dropped. This would cause the original
thread to never exit the span,. and the thread to which the `Entered`
guard was sent would exit a span that it never observed an enter for.
This is incorrect.

## Solution

This PR adds a `*mut ()` field to `Entered` so that it no longer
implements `Send`. There's now a manual `Sync` impl so structs holding
an `Entered` can still be `Sync`.

Fixes #698

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

File: examples/examples/hyper-echo.rs [hunk 1]
```diff
@@ -16,78 +16,75 @@ async fn echo(req: Request<Body>) -> Result<Response<Body>, hyper::Error> {
...
+            (&Method::POST, "/echo/reversed") => {
+                async move {
+                    let body = hyper::body::to_bytes(req).await?;
+                    let reversed = body.iter().rev().cloned().collect::<Vec<u8>>();
+                    debug!(
+                        body = ?str::from_utf8(&body[..]),
+                        "reversed request body"
+                    );
+                    *response.body_mut() = Body::from(reversed);
+                    info!( body = ?(&response.body()), "response");
```
Comment (davidbarsky) [inline examples/examples/hyper-echo.rs:67]: Extra space after the `info!(`.

**Review by davidbarsky — APPROVED** [review]

File: examples/examples/hyper-echo.rs (hunk 1 above)
Comment (hawkw) [reply examples/examples/hyper-echo.rs:67]:
```suggestion
                    info!(body = ?(&response.body()), "response");
```

File: tracing/src/span.rs [hunk 2]
```diff
@@ -379,6 +380,7 @@ pub(crate) struct Inner {
 #[must_use = "once a span has been entered, it should be exited"]
 pub struct Entered<'a> {
     span: &'a Span,
+    _not_send: PhantomData<*mut ()>,
```
Comment (MikailBag) [inline tracing/src/span.rs:383]:
```suggestion
    _not_send_but_sync: PhantomData<std::sync::MutexGuard<'static, ()>>,
```
It's a bit weird, but -1 unsafe.

Comment (hawkw) [reply tracing/src/span.rs:383]: oh that's clever! thanks!

unfortunately we can't do *exactly* what you've suggested, because this needs to compile with the `std` feature disabled, but I can do something similar.

Comment (LucioFranco) [reply tracing/src/span.rs]: This isn't actually unsafe? We are not dereferencing this type, thus doesn't require unsafe.

Comment (hawkw) [reply tracing/src/span.rs]: @LucioFranco the unsafe was necessary for manually implementing `Sync`.

Comment (hawkw) [reply tracing/src/span.rs]: ...and, it turns out this approach doesn't actually work in this specific case. Because `tracing` has conditional support for `no_std`, we can't use the `std::sync` version of `MutexGuard`. I thought we could use the `MutexGuard` from the spinlock implementation that's used as a fallback on no-std platforms, but I'd forgotten that this is defined in `tracing-core`, not `tracing`, and isn't publicly visible. I'll probably go back to the previous approach of just accepting the additional `unsafe` keyword necessary to manually impl `Sync`.
