### PR TITLE
tracing-journald: Send large journal payloads through memfd

### LINKED ISSUE #1698: tracing-journald ignores EMSGSIZE from send()
## Bug Report

As far as I can see the current implementation of tracing-journal [entirely ignores the error returned from `.send()`](https://github.com/tokio-rs/tracing/blob/1d9b9310ada56fa24f1e81d5c2b5ec9767963c8a/tracing-journald/src/lib.rs#L179):

```
        // What could we possibly do on error?
        #[cfg(unix)]
        let _ = self.socket.send(&buf);
```

However, according to "Basics" in the [systemd protocol documentation](https://systemd.io/JOURNAL_NATIVE_PROTOCOL/) socket datagrams are subject to size limits.  If a datagram exceeds the message size `socket.send` will return an `EMSGSIZE` error. In this case journal clients should write the payload to a sealed memfd instead and send that memfd to journald.

tracing-journald doesn't, so it may silently loose messages.  On my system the limit appears to be about 213Kb according to `/proc/sys/net/core/wmem_max`; I say "appears" because I'm not entirely sure that this `/proc` file is definitely relevant.  In any case the limit seems to be system-specific so I don't think tracing can generally assume that "reasonably-sized" messages fit into a single datagram.  And I don't think tracing should risk loosing messages.

I can make a pull request (mostly copying from the [working impl in libsystemdrs](https://github.com/lucab/libsystemd-rs/blob/de6a920362307b37926a4acbac4f741f6447cf10/src/logging.rs#L188)), but memfds aren't in the standard library and require either a lot of unsafe `libc` code or a `nix` dependency, so I'm not sure what the proper course of action is here.

Cheers,
Basti

### PR DESCRIPTION
**Pull request by lunaryorn**
See #1698: Properly write large payloads to journal.

I'd appreciate a very careful review; this cmsg stuff is nasty, and while it's well documented in `cmsg(3)` I had to fiddle a bit because the corresponding functions in libc aren't const and thus don't permit a direct allocation of the buffer as most `cmsg` C code around does.

Closes #1698

## Motivation

Linux limits the maximum amount of data permitted for a single Unix datagram; sending large payloads directly will fail.

## Solution

Follow systemd.io/JOURNAL_NATIVE_PROTOCOL/ and check for EMSGSIZE from `send()`; in this case write the payload to a memfd, seal it, and pass it on to journald via a corresponding SCM_RIGHTS control message.

Per discussion in #1698 this adds no dependency on nix, and instead implements fd forwarding directly with some bits of unsafe libc code.

### CODE REVIEW

File: tracing-journald/src/memfd.rs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+fn create<S: AsRef<str>>(name: S, flags: c_uint) -> Result<File> {
+    let cname = CString::new(name.as_ref()).map_err(|_| {
+        Error::new(
+            ErrorKind::InvalidData,
+            format!("Name {:?} contains internal NUL byte", name.as_ref()),
+        )
+    })?;
+    unsafe {
+        let fd = memfd_create(cname.as_ptr(), flags);
```
Comment (Ralith) [inline tracing-journald/src/memfd.rs:19]: We only ever pass in a single `name` here, and according to the memfd_create manpage the name has no semantic meaning. Let's use a hardcoded constant (e.g. `b"tracing-journald\0"`) rather than creating a new `CString` on every call.

File: tracing-journald/src/socket.rs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+use std::alloc::{alloc_zeroed, dealloc, Layout};
+use std::io::{Error, Result};
+use std::mem::{align_of, size_of, MaybeUninit};
+use std::os::unix::net::UnixDatagram;
+use std::os::unix::prelude::{AsRawFd, RawFd};
+use std::ptr;
+
+use libc::*;
+
+pub fn send_one_fd<F: AsRawFd>(socket: &UnixDatagram, fd: F) -> Result<usize> {
```
Comment (Ralith) [inline tracing-journald/src/socket.rs:12]: Do we really need to be generic over multiple possible fd carriers here? This is single-purpose code.

File: tracing-journald/src/socket.rs [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+        // as outlined in cmsg(3), but `CMSG_SPACE` is no const function, unfortunately (the corresponding
+        // libc feature `const-extern-fn` requires nightly).
+        //
+        // We allocate zeroed memory to make sure that all padding bytes in CMSG_SPACE are zero.
+        let control_layout = Layout::from_size_align(
+            CMSG_SPACE(size_of::<RawFd>() as u32) as usize,
+            align_of::<cmsghdr>(),
+        )
+        .unwrap();
+        let controlbuf = alloc_zeroed(control_layout);
```
Comment (Ralith) [inline tracing-journald/src/socket.rs:30]: We should put this on the stack. It's okay to hardcode an empirical value based on the behavior of `CMSG_SPACE` on known platforms. We can check the assumption in `Subscriber::new` for safety.

**Review by Ralith — CHANGES_REQUESTED** [review]

File: tracing-journald/src/memfd.rs (hunk 1 above)
Comment (lunaryorn) [reply tracing-journald/src/memfd.rs]: Done.

File: tracing-journald/src/socket.rs (hunk 2 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs:12]: Habit, and then I figured it wouldn't do no harm, but you're right, it's simpler without the generic type parameter.  I've removed it.

File: tracing-journald/src/socket.rs (hunk 3 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs:30]: So you'd like me to go… through all combinations of libc's and architectures to hardcode the values of CMSG_SPACE for these?

I don't think I'd like to do this, to be honest.  I'm sorry but that more effort than I'd like to spend on this merge request, and I don't see the benefit: While I do agree that a stack allocation would be nice and easier to understand this code only gets hit in the rare situation where someone actually sends a few megabytes to the journal.  I don't think this corner case warrants so much effort, and I figure that if you send a couple of megabytes to the journal this little heap allocation won't do no further harm :slightly_smiling_face: 

If you think that it's quite important to do a heap allocation here let's at least do it "right" and try to get libc to promote CMSG_SPACE to a const fn; as far as I can see it's not an extern function so there's no reason why it shouldn't be const  by default.

Comment (lunaryorn) [reply tracing-journald/src/socket.rs:30]: FWIW nix also uses a heap-allocated `Vec`, for the same reason.  

I tend to put the blame on `libc`, to be honest: There's no reason for `CMSG_SPACE` and `CMSG_ALIGN` to be guarded under the const extern fn feature; they aren't extern at all and could trivially be propagated to `const`.

Comment (Ralith) [reply tracing-journald/src/socket.rs:30]: You're right that the performance on this path isn't super important. However, we don't need to determine and hardcode a precise unique size for every possible target, just come up with a plausible upper bound and be prepared to raise it in the future if someone complains. `CMSG_SPACE` is de facto very straightforward, after all--it's just the sum of sizeof(cmsghdr), aligned, with the size of the payload, aligned. If you don't want to think about it any harder, I'm sure a 64 byte buffer will work just fine; we use 88 bytes in Quinn for up to 3 different cmsgs.

File: tracing-journald/src/lib.rs [hunk 4]
```diff
@@ -174,12 +179,34 @@ where
             self.field_prefix.as_ref().map(|x| &x[..]),
         ));
 
-        // What could we possibly do on error?
         #[cfg(unix)]
-        let _ = self.socket.send(&buf);
+        #[allow(dead_code)]
+        let result = self.socket.send(&buf).map_err(|e| e.raw_os_error());
+
+        #[cfg(target_os = "linux")]
```
Comment (Ralith) [inline tracing-journald/src/lib.rs:186]: Maybe at this point it's simpler to `cfg` out the entire function in favor of a stub on nonlinux?

Comment (lunaryorn) [reply tracing-journald/src/lib.rs]: Indeed.  I wanted to keep the structure of the original code, but it's gotten unnecessarily complex.

If moved the whole send logic into a single `send_payload` function which is stubbed out on non-Linux.

File: tracing-journald/src/socket.rs (hunk 3 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs:30]: Oh, I must admit the thought of just not bothering with `CMSG_SPACE` and using a fixed-size buffer instead just did not at all occur to me :innocent: I'll try that right away :slightly_smiling_face:

Comment (hawkw) [reply tracing-journald/src/socket.rs:30]: I have a slight preference for doing this the way Ralith suggests, not because of the performance impact of the heap allocation, but because I think this code would be a bit simpler if we could just use a `repr(C)` union here. But, I agree that it would also be quite unpleasant to hardcode every possible `CMSG_SPACE` value here. I think it's probably fine, though, to just pick the maximum size and alignment that any platform needs, and go with that --- if we waste a few bytes of stack space on other platforms, I don't think that's the end of the world.

File: tracing-journald/src/lib.rs [hunk 5]
```diff
@@ -174,12 +179,39 @@ where
...
+#[cfg(not(target_os = "linux"))]
+fn send_payload(socket: &UnixDatagram, payload: &[u8]) -> std::io::Result<()> {
+    Err(std::io::Error::new(
+        std::io::ErrorKind::Unsupported,
+        "journald not supported on non-Linux OS",
+    ))
+}
+
+#[cfg(target_os = "linux")]
+fn send_payload(socket: &UnixDatagram, payload: &[u8]) -> std::io::Result<usize> {
```
Comment (hawkw) [inline tracing-journald/src/lib.rs:196]: nit: `std::io` is imported in this module, so these could just be:
```suggestion
    Err(io::Error::new(
        io::ErrorKind::Unsupported,
        "journald not supported on non-Linux OS",
    ))
}

#[cfg(target_os = "linux")]
fn send_payload(socket: &UnixDatagram, payload: &[u8]) -> io::Result<usize> {
```

File: tracing-journald/src/memfd.rs [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+use std::os::unix::prelude::{FromRawFd, RawFd};
+
+fn create(flags: c_uint) -> Result<File> {
+    unsafe {
+        let fd = memfd_create("tracing-journald\0".as_ptr() as *const c_char, flags);
+        if fd < 0 {
+            Err(Error::last_os_error())
+        } else {
+            Ok(File::from_raw_fd(fd as RawFd))
+        }
```
Comment (hawkw) [inline tracing-journald/src/memfd.rs:17]: we could limit the `unsafe` block here to just the actual unsafe operation:
```suggestion
    let fd = unsafe { memfd_create("tracing-journald\0".as_ptr() as *const c_char, flags) };
    if fd < 0 {
        Err(Error::last_os_error())
    } else {
        Ok(File::from_raw_fd(fd as RawFd))
    }
```

File: tracing-journald/src/lib.rs (hunk 5 above)
Comment (lunaryorn) [reply tracing-journald/src/lib.rs]: Thanks.  I had to refactor this anyway, because I missed that `UnixDatagram` doesn't exist on non-Unix systems.

File: tracing-journald/src/memfd.rs [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+pub fn seal_fully(fd: RawFd) -> Result<()> {
+    let all_seals = F_SEAL_SHRINK | F_SEAL_GROW | F_SEAL_WRITE | F_SEAL_SEAL;
+    unsafe {
+        let result = fcntl(fd, F_ADD_SEALS, all_seals);
+        if result < 0 {
+            Err(Error::last_os_error())
+        } else {
+            Ok(())
+        }
+    }
```
[the remark this answers is not in the document]
Comment (lunaryorn) [reply tracing-journald/src/memfd.rs]: I've reduced the scope of all unsafe blocks.

File: tracing-journald/src/socket.rs (hunk 3 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs]: @Ralith @hawkw I do agree, and I like the idea of using a fixed-size buffer.

Now, I've tried to implement it but it didn't quite work, and my C & systems foo isn't good enough to figure out what's going on :thinking: 

I'm resolving this conversation, and have added some details at the appropriate place.

File: tracing-journald/src/socket.rs [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+
+use std::io::{Error, Result};
+use std::mem::size_of;
+use std::os::unix::net::UnixDatagram;
+use std::os::unix::prelude::{AsRawFd, RawFd};
+use std::ptr;
+
+use libc::*;
+
+const CMSG_BUFSIZE: usize = 88;
```
Comment (lunaryorn) [inline tracing-journald/src/socket.rs:11]: @Ralith @hawkw I've tried to implement the cmsg stuff along what I've seen in quinn-rs (as recommended by @Ralith ), and the code examples in `cmsg(3)` and related documentation, and I'm seeing something that I don't quite understand:

If I pick a buffer size of 39 or less the fd descriptor makes it to journald and I see the message appearing in the journal, and the new test passes.

But if I pick a buffer size of 40 or higher `sendmsg` returns `EINVAL`.

I don't really understand what's going on, and I find this quite hard to debug :thinking: 

Do you perhaps have any idea or any pointers?  Or is there an obvious mistake in my code?

Comment (hawkw) [reply tracing-journald/src/socket.rs:11]: hmm, that's very strange. i spent some time looking at the `cmsg` and `sendmsg` documentation, and nothing really stood out to me, i'm not sure what's going on here. i'm not particularly familiar with Unix socket APIs, so perhaps @Ralith knows?

Comment (Ralith) [reply tracing-journald/src/socket.rs:11]: The bug is probably that you're setting `msg_controllen = CMSG_BUFSIZE`, when `CMSG_BUFSIZE` is the size of the *buffer*, but `msg_controllen` expects the size of the *message*. You should use `CMSG_SPACE` to compute the correct value for `msg_controllen` for the target platform.

Comment (lunaryorn) [reply tracing-journald/src/socket.rs]: @Ralith Indeed, this works, and `cmsg(3)` actually says that:

image

I was confused by the documentation of the `msghdr` struct in `sys/socket.h`:

image

**Comment by lunaryorn** [comment]
@Ralith @hawkw Thanks for your help with the buffer size issue :pray:  Tests pass now, and I'd appreciate a new review :blush:

**Review by Ralith — APPROVED** [review]
LGTM, thanks!

File: tracing-journald/src/lib.rs [hunk 9]
```diff
@@ -109,6 +114,48 @@ impl Subscriber {
...
+        })
+    }
+
+    #[cfg(not(target_os = "linux"))]
+    fn send_large_payload(&self, _payload: &[u8]) -> std::io::Result<usize> {
+        Err(io::Error::new(
+            io::ErrorKind::Unsupported,
+            "Large payloads not supported on non-Linux OS",
+        ))
+    }
```
Comment (hawkw) [inline tracing-journald/src/lib.rs:143]: honestly, i'm a little unsure why we go out of our way to support `#[cfg(unix)]` environments that are not linux. is it even _possible_ to use `journald` on BSD?

not a blocker for this PR, because we already do this, just a thought.

File: tracing-journald/src/lib.rs [hunk 10]
```diff
@@ -109,6 +114,48 @@ impl Subscriber {
         self.field_prefix = x;
         self
     }
+
+    #[cfg(not(unix))]
+    fn send_payload(&self, _opayload: &[u8]) -> std::io::Result<()> {
```
Comment (hawkw) [inline tracing-journald/src/lib.rs:119]: nit: i believe `std::io` is already imported in this scope:
```suggestion
    fn send_payload(&self, _opayload: &[u8]) -> io::Result<()> {
```

File: tracing-journald/src/lib.rs [hunk 11]
```diff
@@ -109,6 +114,48 @@ impl Subscriber {
...
+        Err(io::Error::new(
+            io::ErrorKind::Unsupported,
+            "journald not supported on non-Unix",
+        ))
+    }
+
+    #[cfg(unix)]
+    fn send_payload(&self, payload: &[u8]) -> std::io::Result<usize> {
```
Comment (hawkw) [inline tracing-journald/src/lib.rs:127]:
```suggestion
    fn send_payload(&self, payload: &[u8]) -> io::Result<usize> {
```

File: tracing-journald/src/lib.rs [hunk 12]
```diff
@@ -109,6 +114,48 @@ impl Subscriber {
...
+            if Some(libc::EMSGSIZE) == error.raw_os_error() {
+                self.send_large_payload(payload)
+            } else {
+                Err(error)
+            }
+        })
+    }
+
+    #[cfg(not(target_os = "linux"))]
+    fn send_large_payload(&self, _payload: &[u8]) -> std::io::Result<usize> {
```
Comment (hawkw) [inline tracing-journald/src/lib.rs:138]:
```suggestion
    fn send_large_payload(&self, _payload: &[u8]) -> io::Result<usize> {
```

File: tracing-journald/src/lib.rs [hunk 13]
```diff
@@ -109,6 +114,48 @@ impl Subscriber {
...
+        Err(io::Error::new(
+            io::ErrorKind::Unsupported,
+            "Large payloads not supported on non-Linux OS",
+        ))
+    }
+
+    /// Send large payloads to journald via a memfd.
+    #[cfg(target_os = "linux")]
+    fn send_large_payload(&self, payload: &[u8]) -> std::io::Result<usize> {
```
Comment (hawkw) [inline tracing-journald/src/lib.rs:147]:
```suggestion
    fn send_large_payload(&self, payload: &[u8]) -> io::Result<usize> {
```

File: tracing-journald/src/socket.rs [hunk 14]
```diff
@@ -0,0 +1,59 @@
...
+fn cmsg_space(s: u32) -> usize {
+    unsafe { CMSG_SPACE(s) as usize }
+}
+
+pub fn send_one_fd(socket: &UnixDatagram, fd: RawFd) -> Result<usize> {
+    assert!(
+        cmsg_space(size_of::<RawFd>() as u32) <= CMSG_BUFSIZE,
+        "cmsghdr buffer too small (< {}) to hold a single fd",
+        cmsg_space(size_of::<RawFd>() as u32)
+    );
```
Comment (hawkw) [inline tracing-journald/src/socket.rs:28]: nit/TIOLI: it might be worth sticking this assertion in a unit test as well, so that we can get a CI failure if it is ever somehow violated?

File: tracing-journald/src/socket.rs [hunk 15]
```diff
@@ -0,0 +1,59 @@
...
+    let mut cmsg: &mut cmsghdr =
+        unsafe { CMSG_FIRSTHDR(&msg).as_mut() }.expect("Control message buffer exhausted");
+
+    cmsg.cmsg_level = SOL_SOCKET;
+    cmsg.cmsg_type = SCM_RIGHTS;
+    cmsg.cmsg_len = unsafe { CMSG_LEN(size_of::<RawFd>() as _) as _ };
+
+    unsafe { ptr::write(CMSG_DATA(cmsg) as *mut RawFd, fd) };
+
+    let result = unsafe { libc::sendmsg(socket.as_raw_fd(), &msg, libc::MSG_NOSIGNAL) };
```
Comment (hawkw) [inline tracing-journald/src/socket.rs:51]: very minor style nit: i notice the `libc::sendmsg` is prefixed with `libc` here, but elsewhere in this file, other libc functions are called without the prefix (via the `use libc::*;` import). i have a slight preference to make this consistent (though this isn't a big deal).

**Review by hawkw — APPROVED** [review]
this looks good to me! i commented on some minor style nits, but i'm happy to merge this PR as-is.

File: tracing-journald/src/socket.rs (hunk 14 above)
Comment (Ralith) [reply tracing-journald/src/socket.rs:28]: Shouldn't it already be exercised by the large payload unit test?

Comment (hawkw) [reply tracing-journald/src/socket.rs:28]: ah, yeah, you're right, never mind!

File: tracing-journald/src/lib.rs (hunk 9 above)
Comment (lunaryorn) [reply tracing-journald/src/lib.rs:143]: I didn't actually think much about this… I used `cfg` to tag where things build, not necessarily where they run :slightly_smiling_face:  

I don't know whether journald works on BSD; I don't know much about other Unix systems, and I must admit that I don't care enough to find out :innocent: 

I can also use a simpler `cfg` matrix which mostly stubs out everything on non-Linux, but I think I'd prefer @Ralith's feedback about this as well :slightly_smiling_face:

File: tracing-journald/src/socket.rs (hunk 14 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs]: It's covered by the payload test, but I've still added a separate unit test now, because I think it's easier to debug that way, and it doesn't really add much.

**Review by hawkw — APPROVED** [review]

**Comment by lunaryorn** [comment]
@hawkw @Ralith Thanks for your review and for merging this :pray:

File: tracing-journald/src/lib.rs (hunk 9 above)
Comment (Ralith) [reply tracing-journald/src/lib.rs]: I don't have terribly strong opinions about how we behave on non-Linux unix so long as it's graceful and complexity is limited; I think it's mostly academic.

File: tracing-journald/src/lib.rs [hunk 16]
```diff
@@ -109,6 +114,48 @@ impl Subscriber {
         self.field_prefix = x;
         self
     }
+
+    #[cfg(not(unix))]
+    fn send_payload(&self, _opayload: &[u8]) -> io::Result<()> {
+        Err(io::Error::new(
+            io::ErrorKind::Unsupported,
```
Comment (CAD97) [inline tracing-journald/src/lib.rs:121]: MSRV is currently set to 1.49 but `io::ErrorKind::Unsupported` was stabilized in 1.53.

This wasn't caught on CI because it's gated behind `#[cfg(not(unix))]` 🙃

Comment (hawkw) [reply tracing-journald/src/lib.rs:121]: ughhh, that's annoying. currently we don't build MSRV on windows (or macOS) to avoid having a really huge number of CI builds... but maybe we should be.

Comment (Ralith) [reply tracing-journald/src/lib.rs:121]: Replacing it with `NotFound` would be fine. We shouldn't panic.

Comment (hawkw) [reply tracing-journald/src/lib.rs:121]: Hmm, #2232 is a breaking change --- if anyone is currently compiling this code across multiple operating systems, the method will suddenly disappear for them. I would be fine with making the entire impl `#[cfg(unix)]` in a future breaking change release, but I think we should fix the MSRV violation without breaking the API in a point release first. Therefore, I would really prefer to maintain the current behavior of returning an error on unsupported operating systems.

If we don't like `NotFound`, we could just use `io::ErrorKind::Other`, which should exist on our MSRV.

Comment (CAD97) [reply tracing-journald/src/lib.rs:121]: > And by the way, did anyone actually hit this MSRV violation in their build?

I "hit" it, but only inasmuch as I was doing a minver check on the repository from windows.

For #2231 I just replaced this with `ErrorKind::Other`.

> MSRV tests on other OSes

I think in general it's fine to assume the Linux build will catch things, as the OS-gated functionality is rare enough, and we can fix violations when they come up.

If we *do* want to check other targets, it should be via cross-compile where possible since linux hosted runner time is cheaper, and just a check is sufficient.

(Ultimately CI-wise this comes back to the downside of a monorepo being testing the entire monorepo to verify a subpackage-local change... though this is sometimes desirable since e.g. tracing-core gets a significant amount of test coverage only from testing of tracing or even tracing-subscriber...)

> don't compile on windows

There are AIUI four reasonable choices (of which only the latter pair are legally semver compatible):

- `#![cfg]` the entire crate to only expose any API on platforms where it makes sense. This is IIRC the approach taken by winapi. Consumers `#[cfg]` their usage.
- `compile_error!` on platforms where the crate doesn't make any sense. Consumers need to use a target-dependent dependency as well as `#[cfg]` their usage.
- `panic!` (or error) entrypoints into the API on unsupported platforms. Consumers `#[cfg]` their usage (or tolerate an error on supported platforms as well).
- Stub functionality on unsupported platforms. IIUC tracing-journald is purely a sink, so stubbing it as `> /dev/null` (`$null`<sub>pwsh</sub>) isn't *wrong*, just perhaps unexpected. Consumers can unconditionally use the API and just implicitly degrade on unsupported platforms.

Comment (Ralith) [reply tracing-journald/src/lib.rs:121]: > I think NotFound would be wrong, semantically; after all, we're not searching for anything here

Semantically, we are searching for `JOURNALD_PATH`. This is the error that will be returned when running on a Unix without journald, and unconditionally when running on Windows.

**Comment by Ralith** [comment]
Probably not worth the trouble since it's dead, yeah. If someone's feeling motivated to make this code pretty, we'd probably be better off just reducing the amount of dead code that gets compiled outright.
