### PR TITLE
subscriber: fix missing space issue

### LINKED ISSUE #474: fmt: missing space between timestamp and level
### Version
```
:; cargo tree | rg tracing
nightly-examples v0.0.0 (/Users/eliza/Code/tracing/nightly-examples)
│   └── tracing v0.1.9
│       ├── tracing-attributes v0.1.4
│       └── tracing-core v0.1.6
├── tracing v0.1.9 (*)
├── tracing-attributes v0.1.5 (/Users/eliza/Code/tracing/tracing-attributes)
├── tracing-futures v0.2.0 (/Users/eliza/Code/tracing/tracing-futures)
│   └── tracing v0.1.9 (*)
└── tracing-subscriber v0.2.0-alpha.2 (/Users/eliza/Code/tracing/tracing-subscriber)
    ├── tracing-core v0.1.6 (*)
    ├── tracing-log v0.1.1
    │   └── tracing-core v0.1.6 (*)
    └── tracing-serde v0.1.0
        └── tracing-core v0.1.6 (*)
    └── tracing-log v0.1.1 (*)
```

### Crates

- `tracing-subscriber`

### Description

The old `tracing-subscriber` formatter used to output a space between the timestamp and level. It seems that it no longer does. This looks fine with 4-character levels (INFO, WARN), but weird with 5-character levels (DEBUG, TRACE, ERROR). 

For example:
Screen Shot 2019-12-17 at 11 28 53 AM

Note that although this doesn't look _terrible_ with ANSI colors, if we turn them off, there's no differentiation between the end of the timestamp & the level.

### PR DESCRIPTION
**Pull request by yaahc**
closes #474

### CODE REVIEW

File: tracing-subscriber/src/fmt/time.rs [hunk 1]
```diff
@@ -219,8 +219,8 @@ where
         write!(writer, "{}", style.suffix())?;
     } else {
         timer.format_time(writer)?;
-        write!(writer, " ")?;
     }
+    write!(writer, " ")?;
```
Comment (hawkw) [inline tracing-subscriber/src/fmt/time.rs]: TIOLI: Maybe this should be 
```suggestion
    writer.write_char(' ')?;
```
rather than the macro?
