### PR TITLE
subscriber: add Filtered::filter_mut

### LINKED ISSUE #1629: Panic after reloading layer, combined with `.with_filter`
### Version

```
├── tracing v0.1.29
│   ├── tracing-attributes v0.1.18 (proc-macro)
│   └── tracing-core v0.1.21
└── tracing-subscriber v0.2.25
    ├── tracing v0.1.29 (*)
    ├── tracing-core v0.1.21 (*)
    ├── tracing-log v0.1.2
    │   └── tracing-core v0.1.21 (*)
    └── tracing-serde v0.1.2
        └── tracing-core v0.1.21 (*)
```

### Platform

```
Linux pc 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux
```

### Description

When layer, wrapped in `reload::Layer`, have a filter, set with `.with_filter` (`my_layer.with_filter(my_filter)`), it will panic on next call to `event!` (`info!` in my case). But if layer built as `my_filter.and_then(my_layer)`, everything works:

```rust
use tracing_subscriber::{filter::LevelFilter, fmt, layer::SubscriberExt, reload, Layer};

fn main() {
    // This version works
    // let reloadable_layer_fn = || LevelFilter::TRACE.and_then(fmt::Layer::new());

    // This version doesn't work
    let reloadable_layer_fn = || fmt::Layer::new().with_filter(LevelFilter::TRACE);

    let (layer, handle) = reload::Layer::new(reloadable_layer_fn());
    let subscriber = tracing_subscriber::registry().with(layer);
    tracing::subscriber::set_global_default(subscriber).unwrap();

    tracing::info!("Before reload");

    handle.reload(reloadable_layer_fn()).unwrap();

    // Panics here
    tracing::info!("After reload");
}
```

I am not sure, whether both implementations of `reloadable_layer_fn ` equal or not, but they both seems work in this case.

I expected: `After reload` is printed

Instead, this happened: panic on printing `After reload`
```
Oct 09 14:59:12.383  INFO tracing_test: Before reload
thread 'main' panicked at 'a `Filtered` layer was used, but it had no `FilterId`; was it registered with the subscriber?', /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/filter/layer_filters.rs:239:9
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:541:12
   1: tracing_subscriber::filter::layer_filters::Filtered<L,F,S>::id
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/filter/layer_filters.rs:239:9
   2: tracing_subscriber::filter::layer_filters::Filtered<L,F,S>::did_enable::{{closure}}
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/filter/layer_filters.rs:248:57
   3: std::thread::local::LocalKey<T>::try_with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
   4: std::thread::local::LocalKey<T>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
   5: tracing_subscriber::filter::layer_filters::Filtered<L,F,S>::did_enable
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/filter/layer_filters.rs:248:9
   6: <tracing_subscriber::filter::layer_filters::Filtered<L,F,S> as tracing_subscriber::layer::Layer<S>>::on_event
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/filter/layer_filters.rs:349:9
   7: <tracing_subscriber::reload::Layer<L,S> as tracing_subscriber::layer::Layer<S>>::on_event
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/reload.rs:96:9
   8: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::event
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/layer/layered.rs:116:9
   9: <alloc::sync::Arc<dyn tracing_core::subscriber::Subscriber+core::marker::Send+core::marker::Sync> as tracing_core::subscriber::Subscriber>::event
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/subscriber.rs:715:9
  10: tracing_core::dispatcher::Dispatch::event
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/dispatcher.rs:517:9
  11: tracing_core::event::Event::dispatch::{{closure}}
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/event.rs:35:13
  12: tracing_core::dispatcher::get_default::{{closure}}
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/dispatcher.rs:331:24
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
  14: tracing_core::dispatcher::get_default
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/dispatcher.rs:328:5
  15: tracing_core::event::Event::dispatch
             at /home/flowneee/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.21/src/event.rs:34:9
  16: tracing_test::main
             at ./src/main.rs:165:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by tfreiberg-fastly**
Partially fixes #1629 (I think making `reload::Handle::reload` work with `Filtered` would be cleaner, but this approach seemed easier to me)

I assumed opening the PR against v0.1.x is correct as I couldn't find the `Filtered` type in master.

I think it'd be sensible to note the fact that `reload::Handle::reload` doesn't work with `Filtered` in the docs somewhere, should I add that?

## Motivation

Changing the filter of a `Filtered` at runtime is currently only possible by replacing it with a new `Filtered` via the `reload::Handle::reload` method.
This currently doesn't work as the new `Filtered` won't receive a `FilterId` (see https://github.com/tokio-rs/tracing/issues/1629).

While it would be desirable to just make that work, it would only be possible via a breaking change (according to Eliza) so this seems like a reasonable (and easy) workaround for now.
(I can't judge whether this method is only useful as a workaround for the bug or if it suits the public API independently)

## Solution

Offer mutable access to the `Filtered::filter` field in the public API. This can be used via the `reload::Handle::modify` method to change the filter inside the existing `Filtered`.

### CODE REVIEW

File: tracing-subscriber/src/filter/layer_filters/mod.rs [hunk 1]
```diff
@@ -470,6 +470,31 @@ impl<L, F, S> Filtered<L, F, S> {
     fn did_enable(&self, f: impl FnOnce()) {
         FILTERING.with(|filtering| filtering.did_enable(self.id(), f))
     }
+
+    /// Gives mutable access to the inner filter,
+    /// which can be used to change the filter
+    /// via the [`reload::Handle::modify`](crate::reload::Handle::modify) method.
+    ///
```
Comment (hawkw) [inline tracing-subscriber/src/filter/layer_filters/mod.rs:477]: how about:
```suggestion
    /// Mutably borrows the [`Filter`](crate::filter::Filter) used by this layer.
    /// 
    /// When this layer can be mutably borrowed, this may be used to mutate the filter.
    /// Generally, this will primarily be used with the 
    /// [`reload::Handle::modify`](crate::reload::Handle::modify) method.
    ///
    /// # Examples
```

File: tracing-subscriber/src/filter/layer_filters/mod.rs [hunk 2]
```diff
@@ -470,6 +470,31 @@ impl<L, F, S> Filtered<L, F, S> {
     fn did_enable(&self, f: impl FnOnce()) {
         FILTERING.with(|filtering| filtering.did_enable(self.id(), f))
     }
+
```
Comment (hawkw) [inline tracing-subscriber/src/filter/layer_filters/mod.rs:473]: if we're going to add a `filter_mut` accessor, IMO, we may as well also add a `filter` accessor as well?
```suggestion

    /// Borrows the [`Filter`](crate::filter::Filter) used by this layer.
    pub fn filter(&self) -> &F {
        &self.filter
    }
    
```

Comment (hawkw) [reply tracing-subscriber/src/filter/layer_filters/mod.rs:473]: (it would also be fine to do this in a follow-up PR, but it's a small enough change that we may as well just do it now, I think)

**Review by hawkw — CHANGES_REQUESTED** [review]
overall, this looks good to me --- thanks!

i had a couple suggestions for the documentation, and i thought we might as well also add an immutable accessor while we're here.

**Comment by hawkw** [comment]
> I think it'd be sensible to note the fact that `reload::Handle::reload` doesn't work with `Filtered` in the docs somewhere, should I add that?

I would probably recommend adding examples to the `reload::Handle` documentation showing its use with `Filtered`, using this method. Then, we can add a note there saying not to use `reload::Handle::reload`, as well. It would be fine to do that in this branch or in a separate one --- up to you!

File: tracing-subscriber/src/filter/layer_filters/mod.rs (hunk 1 above)
Comment (tfreiberg-fastly) [reply tracing-subscriber/src/filter/layer_filters/mod.rs:477]: 👍

File: tracing-subscriber/src/filter/layer_filters/mod.rs [hunk 3]
```diff
@@ -470,6 +470,40 @@ impl<L, F, S> Filtered<L, F, S> {
...
+    /// Borrows the [`Filter`](crate::layer::Filter) used by this layer.
+    pub fn filter(&self) -> &F {
+        &self.filter
+    }
+
+    /// Mutably borrows the [`Filter`](crate::layer::Filter) used by this layer.
```
Comment (tfreiberg-fastly) [inline tracing-subscriber/src/filter/layer_filters/mod.rs:479]: I had to fix some link paths, I checked them all now

File: tracing-subscriber/src/reload.rs [hunk 4]
```diff
@@ -36,7 +36,33 @@ pub struct Layer<L, S> {
     _s: PhantomData<fn(S)>,
 }
 
-/// Allows reloading the state of an associated `Layer`.
+/// Allows reloading the state of an associated [`Layer`](crate::layer::Layer).
+///
+/// # Examples
```
Comment (tfreiberg-fastly) [inline tracing-subscriber/src/reload.rs:41]: I used the same example, I assume that's fine?

File: tracing-subscriber/src/reload.rs [hunk 5]
```diff
@@ -36,7 +36,34 @@ pub struct Layer<L, S> {
...
+/// info!("This will be ignored");
+/// reload_handle.modify(|layer| *layer.filter_mut() = filter::LevelFilter::INFO);
+/// info!("This will be logged");
+/// # }
+/// ```
+///
+/// **Warning:** The [`Filtered`](crate::filter::Filtered) type currently can't be changed
+/// at runtime via the [`Handle::reload`] method.
+/// Use the [`Handle::modify`] method to change the filter instead.
+/// (see <https://github.com/tokio-rs/tracing/issues/1629>)
```
Comment (tfreiberg-fastly) [inline tracing-subscriber/src/reload.rs:66]: Not sure if you want a link to the issue in there or not, I can remove it

Comment (hawkw) [inline tracing-subscriber/src/reload.rs:66]: i would probably put this note in the documentation for the `Handle::reload` method, so that it's obvious to people who are looking at the docs for that method where they can't use it.

File: tracing-subscriber/src/reload.rs [hunk 6]
```diff
@@ -36,7 +36,34 @@ pub struct Layer<L, S> {
...
+/// # Examples
+///
+/// Reloading a [`Filtered`](crate::filter::Filtered) layer to change the filter at runtime.
+///
+/// ```
+/// # use tracing::info;
+/// # use tracing_subscriber::{filter,fmt,reload,Registry,prelude::*};
+/// # fn main() {
+/// let (filtered_layer, reload_handle) =
+///     reload::Layer::new(fmt::Layer::default().with_filter(filter::LevelFilter::WARN));
```
Comment (hawkw) [inline tracing-subscriber/src/reload.rs:50]: nit, take it or leave it: i might split this out, like
```suggestion
/// let filtered_layer = fmt::Layer::default()
///     .with_filter(filter::LevelFilter::WARN);
/// let (filtered_layer, reload_handle) = reload::Layer::new(fiiltered_layer);
```

File: tracing-subscriber/src/reload.rs [hunk 7]
```diff
@@ -36,7 +36,34 @@ pub struct Layer<L, S> {
...
+/// # // specifying the Registry type is required
+/// # let _: &reload::Handle<filter::Filtered<fmt::Layer<Registry>,
+/// # filter::LevelFilter, Registry>,Registry>
+/// # = &reload_handle;
+/// #
+/// info!("This will be ignored");
+/// reload_handle.modify(|layer| *layer.filter_mut() = filter::LevelFilter::INFO);
+/// info!("This will be logged");
+/// # }
+/// ```
```
Comment (hawkw) [inline tracing-subscriber/src/reload.rs:61]: it would be nice to also have an example of reloading a global filtering `Layer`...i'm surprised we don't have that already. but we should probably add that in a follow-up PR, rather than here.

File: tracing-subscriber/src/filter/layer_filters/mod.rs [hunk 8]
```diff
@@ -470,6 +470,40 @@ impl<L, F, S> Filtered<L, F, S> {
...
+    /// [`reload::Handle::modify`](crate::reload::Handle::modify) method.
+    ///
+    /// # Examples
+    ///
+    /// ```
+    /// # use tracing::info;
+    /// # use tracing_subscriber::{filter,fmt,reload,Registry,prelude::*};
+    /// # fn main() {
+    /// let (filtered_layer, reload_handle) =
+    ///     reload::Layer::new(fmt::Layer::default().with_filter(filter::LevelFilter::WARN));
```
Comment (hawkw) [inline tracing-subscriber/src/filter/layer_filters/mod.rs:492]: nit, take it or leave it: i might split this out, like
```suggestion
    /// let filtered_layer = fmt::Layer::default()
    ///     .with_filter(filter::LevelFilter::WARN);
    /// let (filtered_layer, reload_handle) = reload::Layer::new(fiiltered_layer);
```
but, take it or leave it.

**Review by hawkw — COMMENTED** [review]
some more docs suggestions --- sorry for being picky!

File: tracing-subscriber/src/reload.rs (hunk 4 above)
Comment (tfreiberg-fastly) [reply tracing-subscriber/src/reload.rs:41]: do you mean the documentation of the `reload` module or of the crate?

**Comment by tfreiberg-fastly** [comment]
thanks for the review and the suggestions!
