### PR TITLE
core: Implement Display for DisplayValue

### LINKED ISSUE #874: the trait `std::fmt::Display` is not implemented for `tracing_core::field::DisplayValue<&std::string::String>`
### Version
0.1.18

### Description

Below is sample code that compiles fine with:
```toml
[dependencies]
tracing = {version = "0.1", default-features = false, features = [
  "attributes",
  "std",
]}
tungstenite = "0.11.0"
```

```rust
use tracing::trace;
use tungstenite::protocol::Message;

fn main() {
  let msg = Message::Text("blah".into());
  trace!(message = display(&msg));
}
```

The moment I enable the "log" feature the build breaks, complaining about some missing `Display`, which is provided.

```patch
--- Cargo.toml
+++ Cargo.toml
@@ -10,5 +10,6 @@ edition = "2018"
 tracing = {version = "0.1", default-features = false, features = [
   "attributes",
   "std",
+  "log",
 ]}
 tungstenite = "0.11.0"
```

```
error[E0277]: `tracing_core::field::DisplayValue<&tungstenite::protocol::message::Message>` doesn't implement `std::fmt::Display`
 --> src/main.rs:6:20
  |
6 |   trace!(message = display(&msg));
  |                    ^^^^^^^^^^^^^ `tracing_core::field::DisplayValue<&tungstenite::protocol::message::Message>` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `tracing_core::field::DisplayValue<&tungstenite::protocol::message::Message>`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: required by `std::fmt::Display::fmt`
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `foo`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by d-e-s-o**
Fix #874 by implementing `std::fmt::Display` for `DisplayValue`.

Fixes: #874

### CODE REVIEW

File: tracing-core/src/field.rs [hunk 1]
```diff
@@ -495,6 +495,12 @@ impl<T: fmt::Display> fmt::Debug for DisplayValue<T> {
     }
 }
 
+impl<T: fmt::Display> fmt::Display for DisplayValue<T> {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(f, "{}", self.0)
```
Comment (hawkw) [inline tracing-core/src/field.rs:500]: Take it or leave it: consider
```suggestion
        fmt::Display::fmt(f, self.0)
```
instead --- there's some small additional overhead to using a format string in `write!` vs just calling the `Display` implementation directly.

Comment (d-e-s-o) [reply tracing-core/src/field.rs]: I take it. Thanks for the suggestion.

**Comment by d-e-s-o** [comment]
Feel free to merge when you get a chance, @hawkw.

**Comment by d-e-s-o** [comment]
Also, is there an ETA for the next `tracing-core` release?

**Comment by hawkw** [comment]
Could be tonight if you need it --- just need to write a changelog.

**Comment by hawkw** [comment]
And released: https://crates.io/crates/tracing-core/0.1.13

Enjoy!

**Comment by loyd** [comment]
What about `DebugValue`?
```
 --> src/main.rs:3:30
  |
3 |     tracing::info!(message = tracing::field::debug(10), ">>");
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^ `tracing_core::field::DebugValue<{integer}>` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `tracing_core::field::DebugValue<{integer}>`
```

Another solution is a wrapper `Wrapper<V: Value>` and `impl Display for Wrapper<V>` using `Value::record`.

**Comment by loyd** [comment]
What about `DebugValue`?
