### PR TITLE
Use unconnected socket

### LINKED ISSUE #1745: tracing-journald:  Do not connect socket
## Bug Report

Currently tracing-journald subscribers immediately connect to the systemd journal socket.

I believe this implies that the subscriber will permanently fail if the connection to the socket ever drops, e.g. if journald crashes.  I think the subscriber should use an unconnected socket and then use `send_to` to specify the target socket explicitly for every message.  That'd make a subscriber "survive" a journald crash, and it's also what [upstream does](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-journal/journal-send.c#L213)

I can make a pull request (based on #1744) to change this.

### Crates

tracing-journald

### PR DESCRIPTION
**Pull request by lunaryorn**
Lets journald subscribers survive a journald restart.

Closes #1745

## Motivation

Currently the journald subscriber immediately connects to the journald socket.  As such I understand it'd not survive a full restart of journald.

## Solution

Do not connect the client socket immediately; instead pass the socket pathname every time we send a message.  This is also what upstream does.

### CODE REVIEW

File: tracing-journald/src/lib.rs [hunk 1]
```diff
@@ -95,11 +97,14 @@ impl Subscriber {
...
-            socket.connect("/run/systemd/journal/socket")?;
-            Ok(Self {
+            let sub = Self {
                 socket,
                 field_prefix: Some("F".into()),
-            })
+            };
+            // Check that we can talk to journald, by sending empty payload which journald discards.
+            // However if the socket didn't exist or if none listened we'd get an error here.
+            sub.send_payload(&[])?;
```
Comment (lunaryorn) [inline tracing-journald/src/lib.rs:106]: @Ralith I'm not sure whether this is a good idea, but it seems to work as a simple check whether we can talk to journald, as you asked for in #1745 :slightly_smiling_face:

File: tracing-journald/src/socket.rs [hunk 2]
```diff
@@ -31,14 +33,41 @@ fn cmsg_buffer_size_for_one_fd() {
...
+    // We need to take the final NULL byte into account.
+    if path_bytes.len() < addr.sun_path.len() - 1 {
+        unsafe {
+            std::ptr::copy_nonoverlapping(
+                path_bytes.as_ptr(),
+                addr.sun_path.as_mut_ptr() as *mut u8,
+                path_bytes.len(),
+            );
+        }
+        addr.sun_path[addr.sun_path.len() - 1] = 0;
```
Comment (Ralith) [inline tracing-journald/src/socket.rs:50]: This is unnecessary since the sockaddr_un is initially zeroed, and also confusing since it ignores the length of the path.

File: tracing-journald/src/socket.rs [hunk 3]
```diff
@@ -31,14 +33,41 @@ fn cmsg_buffer_size_for_one_fd() {
...
+
+pub fn send_one_fd_to<P: AsRef<Path>>(socket: &UnixDatagram, fd: RawFd, path: P) -> Result<usize> {
     assert_cmsg_bufsize();
 
     let mut cmsg_buffer = AlignedBuffer {
         buffer: ([0u8; CMSG_BUFSIZE]),
     };
     let mut msg: msghdr = unsafe { zeroed() };
 
+    let mut addr = create_sockaddr_un_for_path(path)?;
```
Comment (Ralith) [inline tracing-journald/src/socket.rs:65]: Could we replace this entire function with a constant? [`sockaddr_un`](https://docs.rs/libc/latest/libc/struct.sockaddr_un.html) isn't a complicated structure.

File: tracing-journald/src/lib.rs (hunk 1 above)
Comment (Ralith) [reply tracing-journald/src/lib.rs:106]: I was concerned that journald might do something funny here, but [the shiny new journald protocol docs](https://systemd.io/JOURNAL_NATIVE_PROTOCOL/) explicitly say empty datagrams are ignored, so I think this is perfect.

**Review by Ralith — CHANGES_REQUESTED** [review]
Thanks!

File: tracing-journald/src/socket.rs (hunk 2 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs]: Removed it.

File: tracing-journald/src/socket.rs (hunk 3 above)
Comment (lunaryorn) [reply tracing-journald/src/socket.rs]: I've inlined it.

File: tracing-journald/src/socket.rs [hunk 4]
```diff
@@ -31,18 +33,38 @@ fn cmsg_buffer_size_for_one_fd() {
...
-pub fn send_one_fd(socket: &UnixDatagram, fd: RawFd) -> Result<usize> {
+pub fn send_one_fd_to<P: AsRef<Path>>(socket: &UnixDatagram, fd: RawFd, path: P) -> Result<usize> {
     assert_cmsg_bufsize();
 
-    let mut cmsg_buffer = AlignedBuffer {
-        buffer: ([0u8; CMSG_BUFSIZE]),
+    let mut addr: sockaddr_un = unsafe { zeroed() };
+    let path_bytes = path.as_ref().as_os_str().as_bytes();
+    // path_bytes may have at most sun_path + 1 bytes, to account for the trailing NUL byte.
+    if addr.sun_path.len() <= path_bytes.len() {
```
Comment (lunaryorn) [inline tracing-journald/src/socket.rs:42]: I hope this condition is sufficiently clear?

File: tracing-journald/src/socket.rs [hunk 5]
```diff
@@ -31,18 +33,38 @@ fn cmsg_buffer_size_for_one_fd() {
...
+        return Err(Error::from_raw_os_error(ENAMETOOLONG));
+    }
+
+    addr.sun_family = AF_UNIX as _;
+    unsafe {
```
Comment (lunaryorn) [inline tracing-journald/src/socket.rs:47]: Not sure how to do this in safe Rust, given that I've got a `u8` slice in Rust land and a `c_char` = `i8` array in C land… :thinking:

**Comment by lunaryorn** [comment]
@Ralith @hawkw I think this would be ready for another review :slightly_smiling_face:

File: tracing-journald/src/socket.rs (hunk 4 above)
Comment (Ralith) [reply tracing-journald/src/socket.rs:42]: LGTM.

File: tracing-journald/src/socket.rs (hunk 5 above)
Comment (Ralith) [reply tracing-journald/src/socket.rs:47]: You could write the for loop explicitly (LLVM is supposed to be pretty good at converting such loops into `memcpy` calls anyway) but I think this is fine, in context.

File: tracing-journald/src/lib.rs [hunk 6]
```diff
@@ -86,6 +86,8 @@ pub struct Subscriber {
     field_prefix: Option<String>,
 }
 
+const JOURNALD_PATH: &str = "/run/systemd/journal/socket";
```
Comment (Ralith) [inline tracing-journald/src/lib.rs:89]: Should probably resolve the lint issue here.

Comment (lunaryorn) [reply tracing-journald/src/lib.rs:90]: Done, I think.   I'm waiting for the CI though because I don't have any Windows to test this.

**Review by Ralith — APPROVED** [review]

**Comment by lunaryorn** [comment]
@hawkw Is anything still blocking this pull request? :blush:

**Comment by hawkw** [comment]
> @hawkw Is anything still blocking this pull request? :blush:

Sorry I didn't get back to this sooner, I wasn't feeling well. If it got a +1 from @Ralith, it's probably good in my book...

**Review by hawkw — APPROVED** [review]
looks good to me!
